[build]
  command = "pnpm run build"
  base = "/"
  package = "apps/docs"
  publish = "apps/docs/.next"

[build.environment]
  NETLIFY_USE_PNPM = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"
